### ISSUE TITLE
Examples of script invocations for training and inference?

### ISSUE THREAD

**Issue by yuvalkry** [vagrawal/deepsphinx#5]
Hello!

 Thanks for making the project compatible with python-3 !

 In setup.py, change the script name from 'bin/deepsphinx_train' to
   'bin/deepsphinx-train' .

Could you please provide basic examples of script invocations for training and inference?

I ran 
   python bin\deepsphinx-train --trans-file data\ds-input.txt --nouse-train-lm --job-dir data\train5
and got a division by zero, something was probably wrong in the call.

  Thanks,
          Yuval

INFO:tensorflow:Getting speaker stats
INFO:tensorflow:Starting training
INFO:tensorflow:Epoch completed, saving
INFO:tensorflow:Evaluation started
INFO:tensorflow:Restoring parameters from data\elta\train55\checkpoints/-0
Traceback (most recent call last):
  File "bin\deepsphinx-train", line 270, in <module>
    tf.app.run(train)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\sitepackages\tensorflow\python\platform\app.py", line 48, in run_sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "bin\deepsphinx-train", line 153, in train
    lm_fst)
  File "bin\deepsphinx-train", line 79, in run_eval
    tot_wer / tot_ev, tot_cer / tot_ev))
ZeroDivisionError: float division by zero

**Comment by vagrawal** [comment]
Your training data likely has less examples than batch size.

Sorry for being late for the docs, but I will be surely updating the docs for inference and training and provide a pre-trained model by tomorrow :-) .

**Comment by yuvalkry** [comment]
That would be great!

Does the system support adaptation? can I add training data to a pre-trained model?

Thanks,
    Yuval

**Comment by vagrawal** [comment]
Yes, you can start the training from a pre-trained model, but the vocabulary needs to be the same.

**Comment by vagrawal** [comment]
I have made a tool for inference. Please have a look.

Any more suggestions are highly welcome.
