### ISSUE TITLE
Cannot find the module "flags"

### ISSUE THREAD

**Issue by yuvalkry** [vagrawal/deepsphinx#6]
Hello!

  Thank you for all the improvements and documentation.

  I installed in Ubuntu 
   sudo python3 setup.py build
   sudo python3 setup.py install

then issued the command:

shell: python3 bin/deepsphinx-infer --checkpoint-path data/batch-21937.data-00000-of-00001  --audio-file ~/speech/23-00-25_217c.wav

There was an error - see below:

Traceback (most recent call last):
  File "bin/deepsphinx-infer", line 5, in <module>
    from deepsphinx.api import Predict
  File "/usr/local/lib/python3.5/dist-packages/deepshinx-0.1-py3.5.egg/deepsphinx/api.py", line 7, in <module>
ImportError: No module named 'flags'

Although the module was in the "build"

shell:  find . -name flags*
./build/lib/deepsphinx/flags.py
./deepsphinx/flags.py

The same error occurs also with python3 bin/deepsphinx-infer --help and on Windows.

   Thanks,
      Yuval

**Comment by vagrawal** [comment]
It's strange that it is working in my case. Based on the line, I can guess the error. Can you try again please.

Also, you have to run `deepsphinx-infer --checkpoint-path data/batch-21937 --audio-file ~/speech/23-00-25_217c.wav`(notice the checkpoint path)

Thanks so much for reporting the errors.

**Comment by yuvalkry** [comment]
I ran with the shorter checkpoint path as in your example and got the same result.
Strange because "flags" appears in the build directory.

On ubuntu I am using "python3", could that be the reason?

   Thanks,
           Yuval

**Comment by vagrawal** [comment]
Have you pulled again from the repo? If not, please pull it again and install it.

I don't think python3 is the reason as I am using it too.

**Comment by yuvalkry** [comment]
[err.txt](https://github.com/vagrawal/deepsphinx/files/1273000/err.txt)

Thanks! Now this error is gone - but there are others from TensorFlow.
I am not using a GPU.

Perhaps I there is a problem with the TensorFlow installation? I followed the 
instructions on their page and installed using pip3 .

   Yuval

**Comment by vagrawal** [comment]
Can you please run `ls data/batch-21937.*` to verify that the checkpoints are there?

**Comment by vagrawal** [comment]
There should be an index file and a data file present in that location.

**Comment by yuvalkry** [comment]
There is only one file, it was doenloaded from the link.

בתאריך 3 בספט׳ 2017 18:40,‏ "Vishal Agrawal" <notifications@github.com> כתב:

**Comment by vagrawal** [comment]
You should have two files. I have mentioned that in USAGE.md.

Can you please download:

https://s3.amazonaws.com/deepsphinx/batch-21937.data-00000-of-00001 https://s3.amazonaws.com/deepsphinx/batch-21937.index

I am sorry for the time it took for you to run this program due to many bugs from my side. Hope this will finally make it work for you.

**Comment by yuvalkry** [comment]
It works now, thank you very much!
Sorry I didn't notice the 2nd file in the usage...

  Yuval
